language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
script:
  - bundle exec rspec --color --format progress
  - bundle exec foodcritic -f any --tags ~FC003 --tags ~FC015 --tags ~FC023 .
  - bundle exec rubocop

